#pragma kernel Compute

struct DataPair
{
    float x;
    float y;
    float output;
};

float pointerX;
float pointerY;
float eps;
RWStructuredBuffer<DataPair> dataBuffer;

float mdistance(DataPair data)
{
    return abs(pointerX - data.x) + abs(pointerY - data.y) + eps;
}

//定义线程组大小
[numthreads(16,1,1)]
void Compute (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    float distance = mdistance(dataBuffer[index]);
    dataBuffer[index].output = 1.0f / distance;
   
}
